name: Build Yocto Image

on:
  push:
  pull_request:
  schedule:
    # run every Tuesday at 3 AM UTC
    - cron: "0 3 * * 2"
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout pika-spark/lmp-manifest
        uses: actions/checkout@v4
        with:
          repository: pika-spark/lmp-manifest
          path: 'lmp-manifest'
          ref: pika-spark

      - name: Build Docker image
        run: |
          docker build -t yocto-build ./lmp-manifest

      - name: Check out this repository containing build script
        uses: actions/checkout@v4
        with:
          path: 'yocto_ws'

      - name: Create a new user and assign Yocto workspace
        run: |
          sudo useradd -m builder --uid 1024
          echo "builder:builder" | sudo chpasswd
          sudo usermod -aG sudo builder
          sudo chown --recursive builder:builder ${{ github.workspace }}/yocto_ws 

      - name: Build Yocto image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/yocto_ws:/workdir \
            -u $(id -u builder):$(id -g builder) \
            yocto-build \
            /bin/bash -c "cd /workdir && bash portenta-x8_build.sh"
